name: Benchmark

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: benchmark-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  benchmark:
    uses: MichaelHatherly/julia-benchmark-action/.github/workflows/benchmark.yml@v1
    permissions:
      contents: write
      pull-requests: write
